== Conformance
_(Mandatory for standards)_

=== Conformance classes

This document establishes xx conformance classe(s):

- DGIWG process,
- DGIWG generic xxx process,
- ...

_"DGIWG process"_ class define requirements for defining generic process description
_"DGIWG generic xxx process"_ classes defines generic process descriptions acooding to "DGIWG process". These generic processes can be implemented by OGC WPS standards (verions 1 or 2) or possibliby other geoprocessing APIs.
Annex A lists the conformance abstract tests which shall be exercised on any software
artefact claiming to implement these conformance classes.

[#conf,reftext='{table-caption} {counter:table-num}']
[cols="4",options="header"]
.Conformance classes
!===
|Conformance class name |Operation or behavior | OGC WPS Conformance Test | DGIWG WPS Conformance Test
|DGIWG process   | DGIWG requirement y to z | - | Annex A.1
|DGIWG generic measurement process   | DGIWG requirement y to z | - | Annex A.2.1
|DGIWG generic elevation process   | DGIWG requirement y to z | - | Annex A.2.2
|DGIWG generic xxxx process   | DGIWG requirement y to z | - | Annex A.2.3
!===


=== Backward compatibility
